### ISSUE TITLE
Add external scripts

### ISSUE THREAD

**Issue by cdeanj** [USDA-VS/reference_guided_assembly#1]
Would it be possible for you to upload the external scripts used in this pipeline to a **scripts/** directory in the main repository?

**Comment by stuber** [comment]
Hi Chris,

Are there specific scripts or files you're interested in?  There are files used to seed idvirus.sh.  I should be able to share these but I'll need to check with the PI.  There is also a script, kraken2krona.sh, that is specific to a Kraken flu database being used.  This flu database is from an external collaborator.  I need to ask before sharing.  I'm more than happy to ask though if interested.  Everything else I think is contained in the script, but I may be missing something. 

Thanks,
Tod

**Comment by cdeanj** [comment]
I may have made a mistake. I briefly looked over the code and saw some shell scripts that I didn't recognize like **bbduk**, but that seems to be part of the BBMap package, which I can download. I don't think I'll need the **kroken2krona.sh** script. It looks like I can skip that part of the pipeline if I need to. What does the GetFastaByGI.py script do?

Best,
Chris

**Comment by stuber** [comment]
Yeah, that's my bad.  Just moved it to a public repo.   See link below.

It's a simple script to download FASTA from NCBI accession.

https://github.com/USDA-VS/playground/blob/master/GetFASTAbyGI.py

**Comment by cdeanj** [comment]
Awesome, thanks! I'll let you know if I run into any issues.
