### ISSUE TITLE
Is this a WGS or metagenomics pipeline?

### ISSUE THREAD

**Issue by cdeanj** [USDA-VS/reference_guided_assembly#2]
Hey Tod,

Can you explain to me why you're using Kraken for this pipeline? Can this tool be used for both WGS and metagenomics data?

Best,
Chris

**Comment by stuber** [comment]
Kraken is just used as a separate tool to complement the reference guided assembly (unless flu is being analyzed, then it may serve to bin reads into segments), making sure two separate tools provide the same result.  idvirus.sh is used on WGS represented in FASTQs either in a metagenomics scenario or from a cultured isolate.

**Comment by cdeanj** [comment]
Awesome, thanks!
